service: sparrow

provider:
  name: aws
  region: eu-west-1
  runtime: java8
  stage: production
  stackName: sparrow
  apiName: sparrow
  deploymentBucket:
    name: sparrow-resources
  versionFunctions: false

package:
  artifact: target/sparrow.jar

functions:
  core:
    handler: sparrow.Handler
    name: sparrow
    events:
      - http:
          path: hello
          method: get
          cors: true
