service: sparrow

provider:
  name: aws
  region: eu-west-1
  runtime: java8
  stage: production
  deploymentBucket:
    name: api.gridr.io
  environment:
    tableName:
      Ref: usersTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ usersTable , Arn ]

package:
  artifact: target/sparrow.jar

functions:
  core:
    handler: sparrow.Handler
    name: sparrow
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-finch

custom:
  client:
    bucketName: app.gridr.io
    distributionFolder: resources/public

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
