service: sparrow

provider:
  name: aws
  region: eu-west-1
  runtime: java8
  stage: default
  stackName: sparrow
  apiName: sparrow
  role: sparrowRole
  deploymentBucket:
    name: api.gridr.io

package:
  artifact: target/sparrow.jar

functions:
  core:
    handler: sparrow.Handler
    name: sparrow
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-finch

custom:
  client:
    bucketName: app.gridr.io
    distributionFolder: resources/public

resources:
  Resources:
    sparrowUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sparrow-users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    sparrowRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: sparrow
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: sparrow
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/sparrow:*'
                - Effect: Allow
                  Action:
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/sparrow:*:*'
                - Effect: Allow
                  Action:
                    - dynamodb:DescribeTable
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:dynamodb'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'table/sparrow-users'
